docs(seed-docs): alert dialog
daangn/seed-design pull request #206
Opened 2023-02-21 09:02 UTC by junghyeonsu

2023-03-09 06:52 UTC, junghyeonsu commented
1. What Changed
    - Added new images for overflow and minimum width styles of the alert dialog component.
    - Updated the status of the `react` and `docs` sections in `component-meta.json` from `todo` to `in-progress` and `done` respectively.
    - Added a new section for the design decisions related to color, typography, and layout in `style.mdx`.
    - Added a new section for usage options and interaction guidelines in `usage.mdx`.
    - Updated the description field in `primitive-meta.json`.
    - Added a new section for anatomy, states, contexts, actions, and triggers in `primitive.mdx`.

2. Impact
    - Developers can refer to the added images in `style.mdx` while implementing the styles for the alert dialog component.
    - The updated status of `component-meta.json` gives a better idea of the work progress for the component.
    - Developers can use the design decisions provided in `style.mdx` as guidelines for consistent visual design across the application.
    - The added usage options and interaction guidelines in `usage.mdx` provide better clarity on how to use the component.
    - The updated description in `primitive-meta.json` adds more information about the component for developers.
    - The added anatomy, states, contexts, actions, and triggers sections in `primitive.mdx` help developers understand the functionality of the dialog primitive and implement it easily.

3. Testing
    - Verify that the new images in `style.mdx` reflect the correct styles of the alert dialog component.
    - Verify that the updated status of `component-meta.json` is correct and gives an accurate description of the work progress for the component.
    - Verify that the design decisions provided in `style.mdx` are consistent with the application's visual design and are easy to implement.
    - Verify that the usage options and interaction guidelines in `usage.mdx` are clear and easy to follow.
    - Verify that the added anatomy, states, contexts, actions, and triggers sections in `primitive.mdx` accurately describe the functionality of the dialog primitive and help in its implementation.

2023-03-10 04:52 UTC, malangcat approved these changes

2023-03-10 04:59 UTC, malangcat requested changes

2023-03-10 04:59 UTC, malangcat commented on docs/content/component/alert-dialog/style.mdx
> +| secondary action intent | alternative, neutral, nonpreffered | Secondary 버튼 위계에 대한 옵션 |
issue: 위계 -> 의도
suggestion: Description column을 아예 제거해도 괜찮아요.

2023-03-10 04:59 UTC, malangcat commented on docs/content/component/alert-dialog/style.mdx
> +| Primary Action / Secondary Action | Gap                | 8pt   |
issue: Gap -> Spacing
```suggestion
| Text Container / Action Container | Spacing                | 16pt  |
| Title / Description               | Spacing                | 6pt   |
| Primary Action / Secondary Action | Spacing                | 8pt   |
```

2023-03-10 04:59 UTC, malangcat commented on docs/content/component/alert-dialog/style.mdx
> +
issue: Layout 내용 중간에 Shadow가 들어갔어요.
```suggestion
### secondary action intent=nonpreffered

| Part             | Attribute       | Value  |
| ---------------- | --------------- | ------ |
| Action Container | Align Direction | Column |

### secondary action intent=neutral

| Part             | Attribute       | Value |
| ---------------- | --------------- | ----- |
| Action Container | Align Direction | Row   |

### secondary action intent=alternative

| Part             | Attribute       | Value |
| ---------------- | --------------- | ----- |
| Action Container | Align Direction | Row   |

## 디자인 결정 (Shadow)

| Part    | Attribute   | Value               |
| ------- | ----------- | ------------------- |
| Content | Offset      | 0pt, 5pt            |
|         | Blur Radius | 15pt                |
|         | Spread      | 0pt                 |
|         | Color       | rgba(0, 0, 0, 0.1)  |
| Content | Offset      | 0pt, 9pt            |
|         | Blur Radius | 46pt                |
|         | Spread      | 0pt                 |
|         | Color       | rgba(0, 0, 0, 0.12) |
| Content | Offset      | 0pt, 10pt           |
|         | Blur Radius | 38pt                |
|         | Spread      | 0pt                 |
|         | Color       | rgba(0, 0, 0, 0.15) |
```

2023-03-10 04:59 UTC, malangcat commented on docs/content/primitive/dialog/primitive.mdx
> +## 아나토미
issue: 네이밍 유지해주세요.

2023-03-10 04:59 UTC, malangcat commented on docs/content/primitive/dialog/primitive.mdx
> +## 아나토미
```suggestion
## Anatomy
```

2023-03-10 07:25 UTC, merged